### ISSUE TITLE
YouTube not working anymore?

### ISSUE THREAD

**Issue by rasky** [hoyois/clicktoplugin#101]
Hello,

I'm using:

Yosemite 10.10.1
Safari 8.0.2
ClickToPlugin 3.0 with default killers

I have no flash plugin at all, it's simply not installed. When going to YouTube, after upgrading to Yosemite (though I am unsure of the exact timeframe) many videos now ask me to install Flash or Quicktime if I have ClickToPlugin loaded, while they correctly play with the HTML5 player if I disable ClickToPlugin.

This is just an example:
https://www.youtube.com/watch?v=zr4Fuo3YHqw

![screenshot 2015-01-04 17 03 07](https://cloud.githubusercontent.com/assets/1014109/5606525/936c611e-9433-11e4-8de0-e3606309d770.png)

Can somebody tell me what I am doing wrong? My understanding was that ClickToPlugin would just prevent plugins to run, not also block HTML5 players without even providing a replacement.

**Comment by JohnBlackburne** [comment]
My setup is different as I have Flash installed but I too have noticed Youtube problems just today. If I go to YouTube there's no problems but embeds are no longer working on other some sites. E.g.

http://digg.com/video/climbing-englands-tallest-church

I have to load Flash to view it. But it loads as a HTML video on Youtube:

http://youtu.be/9Mmqz-SQoag

**Comment by hoyois** [comment]
@rasky The YouTube killer is not compatible with AdBlock. One of them must be disabled.

**Comment by rasky** [comment]
@hoyois thanks for the pointer. I would like to use AdBlock on YouTube but not ClickToPlugin. I tried removing the YouTube killer from the killer list, but the linked video still doesn't work (though it works if I disable the whole ClickToPlugin). Can you clarify?

**Comment by hoyois** [comment]
You must restart the extension (this is all explained here, BTW: http://hoyois.github.io/safariextensions/clicktoplugin/help.xhtml#faq_youtubesafari8).

**Comment by rasky** [comment]
Thanks and sorry for having missed the FAQ.

I feel that the default is wrong though as it goes against ClickToPlugin stated goals. I can understand people wanting also a "HTML5 killer", but it should possibly be a different set of scripts, with a separate on/off option. Anyway, thank you very much for the support.

**Comment by hoyois** [comment]
I fully agree, but at this point I'd rather deal with the occasional thread like this one than with the dozens of emails I would get if the YouTube killer was disabled by default! ;)
