### ISSUE TITLE
theverge.com video

### ISSUE THREAD

**Issue by dsemaya** [hoyois/clicktoplugin#102]
It appears that clicktoplugin has never worked with video on theverge.com.  Their site seems to be smart enough to figure out to show their video as flash even when the browser's user agent is iOS.  The videos play fine from iOS without Flash.  I believe their media player is the same as other Vox Media properties.

On top of this it appears that there are issues using clicktoplugin and Adblock simultaneously with theverge.com.  Loading the Flash player never plays video.  I have to either disable plugins entirely or launch Firefox or Chrome to watch the video.

**Comment by hoyois** [comment]
CTP's DOM insertions cause an error in theverge.com's scripts, which is why the video doesn't load after clicking the placeholder. That's a rare occurrence but there's no way to prevent this kind of things from happening. The only way around this is to whitelist the object, I'm afraid.

**Comment by dsemaya** [comment]
How about making clicktoplugin display the HTML5 video that theverge.com shows to iOS devices?

**Comment by hoyois** [comment]
I can't make any promises on killers but you can find instructions for creating them here: http://hoyois.github.io/safariextensions/clicktoplugin/killers.xhtml#create_killers
