### ISSUE TITLE
YouTube not working

### ISSUE THREAD

**Issue by JohnBlackburne** [hoyois/clicktoplugin#104]
I'm seeing two problems. For a few hours everywhere else YouTube isn't working, i.e. not bypassing Flash, on other sites. Here's one with three videos:

http://time.com/3674807/john-oliver-net-neutrality-civil-forfeiture-miss-america/

But I could have picked any of them. It seems not to be recognising it's YouTube as there's no "view on YouTube" option when I right click.

And some but not all YouTube videos are also not working, Here's one

https://www.youtube.com/watch?v=e-ORhEE9VVg

Videos in my channels that I navigate to from the front page are OK. Others aren't that I've tried such as ones down the right of that one aren't OK.

**Comment by JohnBlackburne** [comment]
Another odder example. This works:

https://www.youtube.com/watch?v=9kN7fhWnhdM

This doesn't

https://www.youtube.com/watch?list=PLSZ-7zGEZ6sDaLbGunAvrmgTU0GEDj6hp&x-yt-cl=84503534&x-yt-ts=1421914688&v=9kN7fhWnhdM

It's the same video (a mildly scary trailer for a horror series) except the first link is to it alone, he second is to it in a playlist.

**Comment by JohnBlackburne** [comment]
I don't know why but they're working again; all the above links work as do others which I noticed earlier with problems. Second time something like this has happened. I'll leave this here in case anyone else has some experiences/observations but feel free to close it as there's now nothing to fix.

**Comment by hoyois** [comment]
Sometimes Safari is to blame for these things. It happened to me once recently that embedded/encrypted YouTube videos were not replaced anymore, and that was because Safari failed all its XHR requests to youtube.com. Restarting fixed the problem.
