### ISSUE TITLE
Add plugin for the Nightly Show on Comedy Central

### ISSUE THREAD

**Issue by karasline** [hoyois/clicktoplugin#105]
I was wondering if the Nightly Show with Larry Wilmore could be added to the MTVNetworks killer.

**Comment by hoyois** [comment]
Sure, I just uploaded an updated killer: https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/MTVNetworks.js

**Comment by karasline** [comment]
Tried it out last night and it works.  Thanks!
