### ISSUE TITLE
No longer works on YouTube without Flash installed

### ISSUE THREAD

**Issue by wzxu** [hoyois/clicktoplugin#106]
So now without Flash installed, I get this screen instead of the video.

![Screenshot](https://cloud.githubusercontent.com/assets/5619348/5932189/1f2de110-a6e4-11e4-9cac-d4188b29fed2.png)

Not sure if it was caused by [this recent change (now defaults to HTML5)](http://thenextweb.com/google/2015/01/27/youtube-will-now-default-html5-players-better-support-devices/) on YouTube's side.

**Comment by hoyois** [comment]
Still works here. If you have AdBlock installed make sure you read this: https://github.com/hoyois/safariextensions/issues/8

> Not sure if it was caused by this recent change (now defaults to HTML5) on YouTube's side.

Um. HTML5 has always been the default in Safari 8, I guess this only concerns other browsers.

**Comment by wzxu** [comment]
Oh, I was thinking that maybe their changing the default player somehow affected how the killer works. 

Anyway I'm using uBlock instead of AdBlock. Any idea which rules I might need to whitelist? Perhaps I should file an issue there as well...

Thanks!

**Comment by Diskutant** [comment]
Seems like they fixed that already in the 0.8.6.0-rc.0: https://github.com/gorhill/uBlock/releases

**Comment by ErikSwan** [comment]
Here's the pull request in question: https://github.com/gorhill/uBlock/pull/619
I don't think this has been released yet, though.

**Comment by wzxu** [comment]
Fixed in uBlock 0.8.6.0.
https://github.com/gorhill/uBlock/releases/tag/0.8.6.0
