### ISSUE TITLE
REQ: Chrome extension

### ISSUE THREAD

**Issue by chrisidefix** [hoyois/clicktoplugin#107]
Hi there - I know it's a long shot, but it would be great to get this running under Chrome as well. There is an existing extension, called HTML5ify (https://github.com/lenniboy/html5ify/issues), but it works poorly and doesn't support AirPlay streaming, for example.

Any chance you would like to help me either merging HTML5ify chrome extension framework into this project or merge your website scripts into theirs?

Thanks!

**Comment by hoyois** [comment]
Sorry, I don't have much time for new projects and I have no personal interest in Chrome. I think all you need to do is replace all instances of "safari.something" by their Chrome equivalent.
