### ISSUE TITLE
Videos gone

### ISSUE THREAD

**Issue by aerobatics** [hoyois/clicktoplugin#111]
After installation, I often see the expected blank windows on web pages to click on to get the video content. However, an many websites I do not. Even uninstalling clicktoplugin Safari extension does not return my original behavior. Examples include videos on goggle news, half the videos on swim swam.com (e.g.http://swimswam.com/how-one-arm-backstroke-drill-increases-power-and-reduces-frontal-drag/) (another example, all the videos at http://www.sewingmastery.com/videos/cs6000i/). If I open these web pages using Firefox or Safari on my other Apple computers, the videos are there. It seems Safari on my MacPro is broken.

**Comment by hoyois** [comment]
I'm sorry to hear that but ClickToPlugin can't be the source of the problem if the problem persists after you've uninstalled it. I suggest you ask for help on a specialized forum like discussions.apple.com.
