### ISSUE TITLE
Resuming Safari with some windows that were already open causes some videos to bypass ClickToFlash?

### ISSUE THREAD

**Issue by Basilmir** [hoyois/clicktoplugin#113]
I leave Safari on all the time, and when I log off I put a checkmark in the logout windows so I can have all my windows reopen exactly as they were when I log in again.

When they open, some of the videos are able to bypass "ClickToFlash" and autoplay as they would normally.

Observation. Usually the video is the last thing I was looking at before I logged off and so it's focused and front and center when I log back in.

**Comment by hoyois** [comment]
Interesting, I will try to reproduce it. But I doubt anything can be done, it sounds like a timing issue.

**Comment by Basilmir** [comment]
Yes, probably the Extension takes a little bit to activate and this resume thing happens before that. 


Thanks for the plugin by the way. It should be part of standard safari. Also maybe add a way for people to buy or donate something. It makes 'moderm' web browsing tolerable.

**Comment by hoyois** [comment]
Well, I've had no luck making this happen on my end, maybe because my internet is not able to load pages fast enough...

**Comment by Basilmir** [comment]
I don't think it's internet related, sometimes I'm seeing 5-6 videos making it through on an old ADSL. I have 1gps GPON fiber at my office and while true that the loading time is much faster it just accelerates the symptoms while keeping the distinct differences. 

You have to really push it. 

Try opening about 20 safari windows and give each window some 10 tabs they can all be video, try massive youtube, but it's important that the focused tab remaining in some windows be video. Now minimize to the dock about 15 of them and leave 5 normal size (out of these 5 some 3 must have the focused tab point to a video on youtube). 

Go to Safari preferences and in the first pane choose to have it open all pages you had open last time. 

Now click the apple menu and restart and leave the reopen the windows I had last time checked. 

See if it does it. 

If you have that safari preferences option to reopen enabled you don't have to restart just quit safari and start it again watch it put all windows in the dock and the windows you left open. 


PS. To keep your mac clean, create a new user to properly set this up, which tou can later delete. 

PS1. I'll try to make a video later next week and post it. 


Pe 29 mar. 2015, la 01:47, Marc Hoyois <notifications@github.com> a scris:
