### ISSUE TITLE
Cursor not hiding automatically after going fullscreen

### ISSUE THREAD

**Issue by asoksevil** [hoyois/clicktoplugin#114]
I have set double click as a shortcut for going fullscreen. On CTF 3.0 it worked flawlessly, it would go fullscreen and hide the cursor. On 3.1, the cursor sometimes stays so I have to wait until it goes fullscreen, move around and then it will disappear.

I am not sure under which circumstances it won't fade... but I did see this issue several times.

**Comment by hoyois** [comment]
The extension does not control this. There certainly is no difference between 3.0 and 3.1 in that regard, so you've simply been unlucky in your experiences after the update.
For what it's worth I'm unable to reproduce this now, but I think I remember it happening once in a blue moon.

**Comment by asoksevil** [comment]
@hoyois 

Another issue that I stumbled a couple of days ago is that when you go fullscreen within a few seconds of  playing the video in the HTML5 Player, the video lags and stutters while the audio just plays fine. I have to exit fullscreen and go fullscreen.

Have you experienced this?

**Comment by hoyois** [comment]
No. This is probably because your connection is too slow and unrelated to fullscreen. CTP does not control any of this.
