### ISSUE TITLE
Macworld videos still autoplay on Safari 8.0.4

### ISSUE THREAD

**Issue by mclow** [hoyois/clicktoplugin#115]
2105 13" MacBook Pro.  
Mac OS X 10.10.2 (14C2513)
Safari 8.0.4 (10600.4.10.7)
ClickToPlugin 3.1

Tested with:
          http://www.macworld.com/article/2449808/when-auto-play-videos-play-anyway.html
and    http://www.macworld.com/article/2042704/how-to-block-auto-play-videos.html

If you tell me where the settings for C2P are stored, I'll include them here as well

**Comment by hoyois** [comment]
What's an example of a video that's not blocked?

**Comment by hoyois** [comment]
Do you have Flash installed?

**Comment by mclow** [comment]
a) The videos on the right side of the two pages that I listed start playing. 
b) I do not have flash installed.

**Comment by hoyois** [comment]
Thanks, this is normal then: If you don't have Flash installed these sidebar videos don't use plug-ins, so CTP doesn't interfere.

**Comment by mclow** [comment]
Well, that's unfortunate.   Sorry for the bother.
