### ISSUE TITLE
Youtube killer: playing from a playlist causes HTML 5 conversion to fail

### ISSUE THREAD

**Issue by browndav** [hoyois/clicktoplugin#117]
I'm not sure if this is a known issue or not, but the Youtube killer seems to not like the playlist view. Here's a quick example:

https://www.youtube.com/watch?v=0eUp5Y6eQew&list=PLbtSaIfN60gdUyh6c5B09hk8VzwjFCmUz

The same videos convert just fine when there's no `list` parameter in the URL.

If this is intentional (e.g. the playlist view doesn't work well with the HTML5 player), feel free to close – just wanted to write it down while I had a URL handy and hadn't forgotten yet.

**Comment by hoyois** [comment]
Huh, thanks. That's because the first video in the playlist is not embeddable (a rare occurrence), and the YouTube killer for playlists doesn't work in that case. I can fix that. Still, the result will be a playlist with all entries but the first one grayed out.

**Comment by browndav** [comment]
You're totally right; it's just that playlist. I really should have checked a few others before I filed. Thanks for taking a look.

**Comment by hoyois** [comment]
Fixed in 3.1.2.
