### ISSUE TITLE
Context menu not showing

### ISSUE THREAD

**Issue by robertoschwald** [hoyois/clicktoplugin#118]
Installed latest version on 10.10.3, but I can't get the context menu to show up to be able to stream flash to an AirPlay device. See Screenshot.

![clicktoplugin_context_menu](https://cloud.githubusercontent.com/assets/1519879/7101857/84a4ad78-e06c-11e4-8ed5-795be8617a6f.png)
![clicktoplugin_context_menu2](https://cloud.githubusercontent.com/assets/1519879/7101860/a0f22410-e06c-11e4-91a7-75c8eceaaf20.png)

**Comment by hoyois** [comment]
CTP doesn't allow you to stream Flash to an AirPlay device.
