### ISSUE TITLE
youtube flash vs html5

### ISSUE THREAD

**Issue by LimitlessPotential** [hoyois/clicktoplugin#119]
not quite sure if this is a problem or just me not setting it right but clicktoplugin defaults to flash on youtube and I'd rather it went to html5. Any advice?

**Comment by hoyois** [comment]
http://hoyois.github.io/safariextensions/clicktoplugin/help.xhtml#faq_youtubesafari8

If this doesn't solve the issue, please provide more details (expected result vs actual result).

**Comment by CyberSkull** [comment]
Leaving the YouTube killer enabled prevents YouTube from detecting H.264 support. Compare https://www.youtube.com/html5 before and after enabling the YouTube killer.

**Comment by hoyois** [comment]
Indeed, that's part of the "hack" mentioned in the FAQ. If you don't want that then you also don't need the YouTube killer.

**Comment by nayefc** [comment]
@hoyois When I restore YouTube's player, is it possible to have it show the HTML5 player instead of the Flash one?

**Comment by hoyois** [comment]
@nayefc No.
