### ISSUE TITLE
Slow loading times

### ISSUE THREAD

**Issue by fatherkanye** [hoyois/clicktoplugin#120]
When watching a video in HD in flash it loads fine but when using CTP there is a lot of buffering. I usually deselect and reselect CTP in preferences to sort it out but this is not solving the issue lately. Anything I can do so I can resume using the plugin as normal?

**Comment by fatherkanye** [comment]
Fixed -- was an issue with autoplay being deselected with no preload

**Comment by hoyois** [comment]
Glad to hear it. It's possible that Flash uses more efficient downloading algorithms than Safari's HTML5, which may result in a different experience. In any case, this is beyond my control.
