### ISSUE TITLE
embedded youtube videos on kinja sites.

### ISSUE THREAD

**Issue by MacTheApple** [hoyois/clicktoplugin#121]
For some reason, with flash to html5 substitutions on, all the youtube videos posted to kinja sites  (gizmodo, koutaku, etc) disappear, leaving no placeholder, just a blank space where the video should be.

**Comment by hoyois** [comment]
Link?

**Comment by MacTheApple** [comment]
Nevermind- traced it down to a different plugin called "google disconnect" that was compatible with my old youtube converter (youtube5) but appears to be incompatible with clicktoplugin's converter.
