### ISSUE TITLE
Issue with playing videos at google photos

### ISSUE THREAD

**Issue by hiwaryi** [hoyois/clicktoplugin#123]
When I try to play videos at google photos page, it says "invalid parameter".
To play videos, I have to disable cicktoflash

**Comment by hoyois** [comment]
Thanks for the report! The YouTube killer is the cause of the problem. The following updated version should fix the problem: https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTube.js

**Comment by hoyois** [comment]
This should be fixed in v3.1.3.
