### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by asoksevil** [hoyois/clicktoplugin#124]
Just realized that when it automatically plays next videos in a playlist, the "main window" does not update with the new video´s title.

For instance: 

![captura de pantalla 2015-06-07 a la s 22 08 41](https://cloud.githubusercontent.com/assets/739697/8026097/d19c99f2-0d61-11e5-85dc-7d827518fc4b.png)

This one should be saying Vanessa Carlton - Ordinary Day instead of Jesse McCartney - Beautiful Should (Video) which was the first one to play.

**Comment by hoyois** [comment]
Yes, that's the way it is. By design CTP is not allowed to modify web pages outside of the div which replaces the plugin.
