### ISSUE TITLE
Security implications of Initial Behavior setting

### ISSUE THREAD

**Issue by Matvei27** [hoyois/clicktoplugin#125]
Can someone explain the security implications of the following settings:

Initial behavior [Do not preload | Preload | Autoplay]
Choose whether ClickToPlugin creates media elements with the preload attribute set to none, to auto, or with the autoplay attribute. With the “Do not preload” option selected, the video only starts buffering when the “Play” button is clicked.

Instant autoplay
Check this (regardless of the previous setting) if your internet connection can download videos in real time or faster. This overrides Safari’s default autoplay behavior which is to initiate playback when the canplaythrough event is fired; instead playback will begin as soon as possible.

**Comment by hoyois** [comment]
I don't think either of those settings have any security implications. What are you worried about?
