### ISSUE TITLE
Macworld.com videos not blocked

### ISSUE THREAD

**Issue by aptagood** [hoyois/clicktoplugin#126]
The video on this page, "How to copy items between your Mac and iPad using AirDrop" http://www.macworld.com/article/2946574/how-to-get-el-capitan-features-without-upgrading-to-el-capitan.html#tk.nl_mwbest
(and videos on http://www.macworld.com/video/)
is not blocked by Clicktoplugin.  The Flash placeholder is visible but the video starts anyway on top of the placeholder.  Oddly, the advertisement that would load before displaying the video doesn't appear.

I'm running ClickToPlugin 3.1.5 and have verified that all the options are set to block this video.  This is the only website I've found where this problem occurs.  

Here's a screenshot of the video frame in http://www.macworld.com/video :
![macworld video](https://cloud.githubusercontent.com/assets/11530868/8659935/de2190ca-2962-11e5-9d45-128b21b2219e.png)

**Comment by hoyois** [comment]
These are HTML5 videos.

**Comment by aptagood** [comment]
Yes, but why do these videos start automatically?  All other HTML5 videos I've seen start only when I click on them.
Is there a way to change this behavior?
These are my settings:






Thanks!

**Comment by hoyois** [comment]
They start automatically because the person who designed the webpage thought it was a good idea to have videos start automatically. You might want to complain there. CTP offers no way to block HTML5 videos.
