### ISSUE TITLE
Does not work with YouTube if flash player is not installed

### ISSUE THREAD

**Issue by toco** [hoyois/clicktoplugin#127]
When the Flash Player plugin is not installed on the computer, YouTube doesn't work with ClickToPlugin activated.
I tried various ClickToPlugin settings but YouTube does not work unless I deactivate ClickToPlugin.

OS X 10.10.4
Safari 8.0.7
ClickToPlugin 3.1.5

**Comment by hoyois** [comment]
Did you read this? http://hoyois.github.io/safariextensions/clicktoplugin/help.xhtml#faq_youtubesafari8

**Comment by toco** [comment]
Thanks, I haven't see that. Disabling the "killer" and restarting Safari fixed the issue for me.
