### ISSUE TITLE
YouTube doesn't record history

### ISSUE THREAD

**Issue by nayefc** [hoyois/clicktoplugin#128]
Does anyone know why video played in the HTML5 player, YouTube doesn't record it in the history, without right clicking and pressing Load Flash?

**Comment by hoyois** [comment]
YouTube only knows that you're watching the video if you're using YouTube's player. If you use CTP's player instead, the trigger for being recorded in history doesn't happen. 

The YouTube killer contains an [initialization script](https://github.com/hoyois/plugin-to-html5/blob/master/YouTube.js#L298) which is run directly after CTP's video player loads. You can probably add history-recording to this script, though I don't know how.
