### ISSUE TITLE
MTVNetworks killer no longer working on The Daily Show, The Nightly Show, etc.

### ISSUE THREAD

**Issue by karasline** [hoyois/clicktoplugin#130]
It would appear that during their hiatus the past two weeks, the comedy central shows changed their interface yet again.  The killer no longer works.  I believe the url's associated with the streams have changed.

**Comment by hoyois** [comment]
Thanks, will investigate.

**Comment by hoyois** [comment]
Can you try this one?

https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/MTVNetworks.js

**Comment by JohnBlackburne** [comment]
Came here to report the same problem, the updated killer fixes it

**Comment by hoyois** [comment]
Nightly Show needed some further updating, just did that now.

**Comment by karasline** [comment]
Daily Show and Nightly Show are now working, under 10.6.8 and 10.10.4.  Thanks very much.

**Comment by hoyois** [comment]
Fixed in CTP 3.1.6.
