### ISSUE TITLE
v3.1.5 does not work with dailymotion(html5)

### ISSUE THREAD

**Issue by Roy75117** [hoyois/clicktoplugin#131]
dailymotion seems renew their player, thus v3.1.5 does not work fine to load default html5 player(mp4) for dailymotion source.

**Comment by hoyois** [comment]
It seems to work for me. Link?

**Comment by Roy75117** [comment]
http://www.dailymotion.com/video/k3jwtqaz3Gq6wzc9VeX
http://www.dailymotion.com/video/k2hfghRn4tETz2cagtO
http://www.dailymotion.com/video/k1NpdS8szKbvzOcaxwG

**Comment by hoyois** [comment]
These are restricted videos, the killer doesn't work on them. That's not new, unless the videos were made restricted recently.

**Comment by Roy75117** [comment]
Got it. However, still tried other recommended video showed in homepage but all in vain. I will keep trying other video.

**Comment by hoyois** [comment]
Is any of those not private (privée)?

**Comment by Roy75117** [comment]
http://goo.gl/ICP5v0
http://goo.gl/4IF6L5
http://goo.gl/rcaob1
I think these are not private but killer does not work.

**Comment by hoyois** [comment]
These work for me. Can you access the following page? http://www.dailymotion.com/embed/video/x2yzykq

**Comment by Roy75117** [comment]
http://i.imgur.com/4r0EHfp.png

I can access it but killer does not work.

BTW, killer works fine with youtube for me.

**Comment by hoyois** [comment]
Fixed now in 3.1.6, thanks!

**Comment by ballo** [comment]
It only works using embedded links. 

If there is a way to force flash, it might work with regular links
