### ISSUE TITLE
PDF files don't open

### ISSUE THREAD

**Issue by reedptaylor** [hoyois/clicktoplugin#134]
PDF files don't open when clicktoflash is enabled.

**Comment by hoyois** [comment]
PDFs in Safari are unaffected by extensions. The problem must be something else...

**Comment by reedptaylor** [comment]
When I right click and click "Disable Click2Flash" and open a PDF link I can view the PDF however when it is enabled, it is just a blank page.

**Comment by hoyois** [comment]
Are you using a plugin to view PDFs on Safari?

**Comment by reedptaylor** [comment]
I only have Click2Flash, 1Password, and AdBlocker.

**Comment by hoyois** [comment]
These aren't plugins. I mean Adobe Reader or something similar.

**Comment by reedptaylor** [comment]
No I don't have any PDF plugins.

**Comment by hoyois** [comment]
Can you share the PDF link you're trying to open?

**Comment by reedptaylor** [comment]
http://adcdownload.apple.com/Developer_Tools/Xcode_7_beta_6/Xcode_7_beta_6_Release_Notes.pdf
It does this with all PDFs though. Heres a video.
https://www.dropbox.com/s/8iako1cy2vw6rjq/PDF%20example.mov?dl=0

**Comment by hoyois** [comment]
The links you're clicking in this video are not direct links to PDF files. Just to be sure, does the same problem happen with this PDF: http://arxiv.org/pdf/1508.05394.pdf

**Comment by reedptaylor** [comment]
Yeah that still leads to a blank page with Click2Flash enabled.

**Comment by hoyois** [comment]
Did you copy the link and open it manually rather than clicking on it?
Also, are you using a beta of Safari?

**Comment by reedptaylor** [comment]
I have tried both and no I am running 8.0.8

**Comment by hoyois** [comment]
Well, then I have no idea what could cause this problem. Certainly no Safari extension is to blame since they don't have any effect on PDF viewing.

**Comment by reedptaylor** [comment]
Uninstalled and reinstalled Click2Flash. Fixed it. Should have tried that a long time ago haha

**Comment by RandomDSdevel** [comment]
@hoyois:  I've just realized and/or figured out (after a short extension debugging session involving toggling different ones on and off) that I've been seeing this behavior again with relatively recent builds of Safari (versions 10 and above, roughly&thinsp;—&thinsp;I'm on Safar v10.1.1 right now.)  Uninstalling ClickToFlash and reinstalling a fresh copy of it downloaded from this project's non-GitHub web page didn't work.  _I_ certainly have absolutely _no_ idea how ClickToFlash could _possibly_ interfere with Safari loading its Preview-based PDF-reading plug-in, though, either, so I _may_ just have to go find and use some other extension (not that I _want_ to, of course, as ClickToFlash has suited me perfectly well until now…)  (I have one idea, but it's not likely.)  

P. S.:  Should I, perchance, have opened a new issue to report this…?
