### ISSUE TITLE
New YouTube HTML5 player is not loaded

### ISSUE THREAD

**Issue by codeclown** [hoyois/clicktoplugin#135]
I've been wondering why I haven't gotten the new transparent YouTube player. Turns out I get it if I turn off clicktoplugin.

I tried fiddling with the settings and disabling flash from Safari (8.0.8 on Mavericks), with no luck.

Would be great to have the HTML5 experience, since I'm nowadays getting lag from flash open. Is it possible to do with the plugin?

**Comment by hoyois** [comment]
Sure, remove the YouTube killer from the list:
http://hoyois.github.io/safariextensions/clicktoplugin/help.xhtml#faq_youtubesafari8

**Comment by codeclown** [comment]
Oh, thanks! I actually tried that but did not restart Safari afterwards.
