### ISSUE TITLE
Flash video is auto playing on macworld.com

### ISSUE THREAD

**Issue by mretondo** [hoyois/clicktoplugin#137]
The below link has a flash video that auto loads and plays. I've been using ClickToPlugin for a long time and this is the first time this has happened. The video on the main page i.e. macworld.com doesn't auto play.

http://www.macworld.com/article/2950474/ios/ios-9-five-small-features-that-will-change-your-life.html

**Comment by hoyois** [comment]
It's actually an HTML5 video.

**Comment by mretondo** [comment]
Oh thanks, but shouldn't it not play as well?

**Comment by hoyois** [comment]
CTP has no control over HTML5 videos.

**Comment by mretondo** [comment]
Didn't know that, thanks
