### ISSUE TITLE
Youtube auto loading ad videos in the background

### ISSUE THREAD

**Issue by jgoldshlag2** [hoyois/clicktoplugin#139]
For the past month or so, I've noticed that when I pull up a youtube video it autoplays an ad in the background, no matter what I do with the clicktoplugin HTML5 player. I don't see the visuals of the video, I just get the audio out of my speakers. 

I just disabled all browser extensions except c2p and the behavior persists. I have c2p set to not autoplay anything and have nothing in my whitelists or "always allow" lists.

**Comment by hoyois** [comment]
I don't experience this. This must be the HTML5 video ad running behind the Flash object, so it sounds like a YouTube bug. Are there any errors in the web console?

**Comment by jgoldshlag2** [comment]
I had a video do this today but I closed the tab before I remembered to pull up the error console. I'll keep my eyes peeled for it in the future. I tried reloading the tab but no ad played in the background like it had been.

**Comment by jgoldshlag2** [comment]
[Warning] Invalid CSS property declaration at: * (www-player-new-vflgvrG-S.css, line 1)

I just had a video load in the background (in this case it actually wasn't an ad but another youtube video altogether). It kicked the above error at me, but that was the only thing in the web console.

**Comment by jgoldshlag2** [comment]
I had it happen again, but there were only warnings and no errors in the console. Here's what I got:

[Warning] Unexpected CSS token: : (www-core-vflJ409_O.css, line 1, x3)
[Warning] Invalid CSS property declaration at: * (www-core-vflJ409_O.css, line 1, x2)
[Warning] Unexpected CSS token: : (www-core-vflJ409_O.css, line 1)
[Warning] Invalid CSS property declaration at: * (www-core-vflJ409_O.css, line 1, x3)
[Warning] Unexpected CSS token: : (www-core-vflJ409_O.css, line 1, x4)
[Warning] Invalid CSS property declaration at: * (www-core-vflJ409_O.css, line 1)
[Warning] Invalid CSS property declaration at: * (www-player-new-vflgvrG-S.css, line 1)
[Warning] Unexpected CSS token: : (www-pageframe-vfl4n7yi0.css, line 1, x3)

**Comment by hoyois** [comment]
I don't think these warnings are related to the problem. Visiting a YouTube page on Safari 8+ with the YouTube killer enabled is like visiting it with a browser with no HTML5 video capabilities (more precisely, the canPlayType function always returns ""). This makes YouTube fall back to Flash for the main video. I guess their code for HTML5 ads is more careless, and as a result it sometimes lets HTML5 video ads run concurrently with the Flash object. Doesn't happen here though, maybe timing is also involved.

**Comment by antkn33** [comment]
This happens to me too. I am using version 3.16 on Safari 8.0.8. Thanks

**Comment by swooshswoosh** [comment]
Is happening to me too.

**Comment by sonium0** [comment]
uBlock fixes this for me (Ghostry does not)

**Comment by swooshswoosh** [comment]
@sonium0 Thanks for the tip!

**Comment by peelman** [comment]
Having the same issue.  Ads playing in background.  Attempts to hunt down the source tag in the code have been fruitless for me so far.

**Comment by hoyois** [comment]
@peelam That would be useful indeed. If you just copy the whole HTML from the DOM inspector while the ad is playing, you should be able to find it in there.

**Comment by aqres** [comment]
Same issue here too

**Comment by hoyois** [comment]
Can someone tell me if the following killer fixes the issue?

https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTube.js

**Comment by peelman** [comment]
Is there an easy way to drop that file in for testing?

**Comment by hoyois** [comment]
@peelman Simply replace "killers/YouTube.js" by the above URL in CTP's preferences. The new killer will be loaded when you exit the preferences.

**Comment by hoyois** [comment]
This should be fixed in 3.1.8.
