### ISSUE TITLE
BBC stopped working again

### ISSUE THREAD

**Issue by JohnBlackburne** [hoyois/clicktoplugin#140]
For a few days BBC news videos have stopped working. E.g. this one

http://www.bbc.co.uk/news/world-europe-34301414

Though any and all of those down the right hand side seem to have this problem. Instead I have to load Flash to see them. I've restarted Safari and the Mac since first noticing it but the problem persists. Latest Mac OS and Safari.

**Comment by hoyois** [comment]
Bummer, the video URLs used by the killer have been removed, only rtmp feeds are left. We need a different way to get video URLs (I don't know how to get the URLs served to iOS either). Any ideas are welcome.

**Comment by JohnBlackburne** [comment]
Yes, of course it works if I pretend to be on an iPad, which I may start doing as since they updated the site it largely doesn't care what device you are on. Looking at the video URL and I would not know where to start.

**Comment by aqres** [comment]
Noticed this too.  Sad to see this as CTP really saved my cPU with BBC vids

**Comment by JohnBlackburne** [comment]
Crazily the BBC has now decided to move to HTML 5, but excluding Safari on the desktop. Tell it though you are using another browser (pretty much any other it seems) and you can opt in here:

http://www.bbc.co.uk/html5

Once opted in it works in desktop Safari just fine.

This is just iPlayer at the moment but the intention surely is to move all their content to HTML 5 so they can drop Flash.

**Comment by aqres** [comment]
Not sure if I've woken up particularly dim-witted this morning but what is this "opting in" you speak of ?

**Comment by JohnBlackburne** [comment]
Set your User Agent to something other than Safari on Mac OS. Safari on iPad worked for me. Vist the link I posted. Then there’s a button to opt in. Click it, and once you have go to their iPlayer pages and you are presented with HTML5 rather than Flash.

Does not affect the news videos which ClickToPlugin dealt with, but keep your User Agent set to iPad and they use HTML5 too.

**Comment by hoyois** [comment]
Should be fixed by

https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/BBC.js

I'll update the extension soon.

**Comment by hoyois** [comment]
Fixed in CTP 3.1.7.
