### ISSUE TITLE
Q. Where are the settings saved?

### ISSUE THREAD

**Issue by inket** [hoyois/clicktoplugin#143]
Where are the settings saved?

I fresh-installed El Capitan and now I'm trying to restore the ClickToPlugin settings from a backup but I can't find the files. Other extensions use the `LocalStorage` & `Databases` folders in `~/Library/Safari/`, but what about CTP?

**Comment by hoyois** [comment]
CTP uses the default mechanism for storing extension settings (which is neither LocalStorage nor Databases). You will find them in ~/Library/Preferences/com.apple.Safari.Extensions.plist.

**Comment by inket** [comment]
Thank you so much!
