### ISSUE TITLE
Can't get ClickToPlugin or ClickToFlash to install

### ISSUE THREAD

**Issue by mymacmini** [hoyois/clicktoplugin#144]
I formerly had ClickToFlash working fine. A few weeks ago, I removed it in order to switch to ClickToPlugin, and now I can't get either one to install.

I double click on the extension, then click "Trust" in the pop-up dialog, and have had zero luck getting any further. Neither plug-in ever shows up in the installed extensions list. The process doesn't give me any sort of error, it simply fails to load, and Flash keeps loading.

Any advice?

I'm using Safari 9.0.1 on OS 10.11.1(Beta)

Thanks in advance,

mm

**Comment by hoyois** [comment]
You can try to trash ~/Library/Safari/Extensions.plist.
But in any case you should report this bug to Apple!

**Comment by mymacmini** [comment]
I filled out an OS X beta "Send feedback to Apple" ticket after doing what you recommended and seeing that the issue was not resolved.

Any further steps you'd recommend?

—
Ls

**Comment by mymacmini** [comment]
I found ClickToFlash on Apple's website after entering via the Feedback dialogs and it successfully installed. 

For some reason, I was unable to find it by clicking on the Extension menu option in Safari, and the version I was attempting to install was from your website, not Apple's.

The version found at Apple was installed and is working, so I think we can consider this issue resolved.
—
Ls

**Comment by hoyois** [comment]
CTF is only in the old gallery, not the new one. Installing from there should be equivalent to double-clicking on a safariextz file, however, so I think this was just a fluke. You should look for an update to the latest version of CTF in Safari's preferences.

**Comment by alpxp** [comment]
I have exactly the same issue. Double click on the extension, then click "Trust", then nothing.
Fixed by searching for ClickToFlash in old gallery and then updating in Safari's preferences.

**Comment by fiery-** [comment]
It seems that this is a problem with El Capitan 10.11.1 where safariextz files can't be installed. Extensions install fine in SAFE mode (holding Shift key while restarting):
https://discussions.apple.com/message/29224002#29224002
