### ISSUE TITLE
MutationObserver needs to be disconnected

### ISSUE THREAD

**Issue by zbirkenbuel** [hoyois/clicktoplugin#146]
The MutationObserver that is added to each element is never disconnected.  When a user clicks to enable an element, the tracking record (`_[elementID]`) is deleted but the observer is never disconnected.  If the observer fires again there is a null ref exception when trying to access `_[elementID].parentNode`) (https://github.com/hoyois/clicktoplugin/blob/master/ClickToPlugin.safariextension/main.js#L445).

That either needs to be safety checked or the observer needs to be disconnected whenever a tracking record is deleted.

**Comment by hoyois** [comment]
Good point, thanks! I mistakenly assumed the observer would be garbage collected, but I guess it's still referenced by the node.

**Comment by hoyois** [comment]
Fixed in CTP 3.1.7.
