### ISSUE TITLE
Add option to copy source website URL

### ISSUE THREAD

**Issue by poweruser82** [hoyois/clicktoplugin#148]
In the shortcut menu there is the option to open the original page of an embedded video. I'd like to have an option to copy the URL of that page without opening it before.

**Comment by hoyois** [comment]
Right click > Copy Link.

**Comment by poweruser82** [comment]
I can't see it
![schermata 2015-10-23 alle 09 20 44](https://cloud.githubusercontent.com/assets/325193/10686747/8bf26b3a-7967-11e5-89f0-2357b2c5d069.png)

**Comment by poweruser82** [comment]
I found a workaround for YouTube:
If I enable the option to display the web page in the source selector, I can copy it from there.

**Comment by hoyois** [comment]
That's what I meant actually.

**Comment by poweruser82** [comment]
It's fine for me. Thank you. :)
I'm closing the issue.
