### ISSUE TITLE
Click to flash doesn't work with The Verge videos

### ISSUE THREAD

**Issue by willco007** [hoyois/clicktoplugin#151]
Go to this page:
http://www.theverge.com/2015/10/27/9618630/twitter-tv-ad-chiat-day

Then click the video to load it, it will show the loading spinner but never actually load.  Whatever their player is doing it doesn't like click to flash. :(

**Comment by hoyois** [comment]
Yes, that's because the Flash player initializes some JS variables. The only way for this player to work is if it's not blocked, so you have to whitelist it. Not all Flash can be blocked without side effects...
