### ISSUE TITLE
clicktoflash youtube problems on safari

### ISSUE THREAD

**Issue by a-greyyyyy** [hoyois/clicktoplugin#152]
the last few days i've been getting error notifications on at least half the youtube videos I've tried watching. i disabled ctf, and they play just fine with the native youtube player... anyone else having this issue?
![screen shot 2015-11-10 at 7 14 00 pm](https://cloud.githubusercontent.com/assets/15793940/11083021/450b4f8a-87df-11e5-8d47-cae4a8cbc4fc.png)

**Comment by a-greyyyyy** [comment]
another example... this seems to be happening specifically on music videos, but not all of them.
![screen shot 2015-11-10 at 7 34 01 pm](https://cloud.githubusercontent.com/assets/15793940/11083263/24baacd2-87e2-11e5-9246-d359c62c13a1.png)

**Comment by hoyois** [comment]
Thanks for the heads up, this is a small problem with the signature decryption mechanism. It's probably going to work again in a couple of days when YouTube updates its signatures. In the meantime, either of the following killers fixes the issue:

https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTube.js
https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTubeXHR.js

**Comment by a-greyyyyy** [comment]
i hate to sound ignorant, but i don't know how to install killers in the script for this extension...

is there a tutorial available?

**Comment by a-greyyyyy** [comment]
figured out how to install them, found your tutorial... all the videos are playing now.

thank you!

**Comment by dmelgar** [comment]
How do you install killers?

**Comment by Diskutant** [comment]
I have the same problem with some videos but the 2 killers hoyois mentioned don't help.

Example: https://www.youtube.com/watch?v=JRvPUnFYcFA

**Comment by hoyois** [comment]
Fixed in CTP 3.1.9.
