### ISSUE TITLE
Seeking fails sometimes

### ISSUE THREAD

**Issue by blackketter** [hoyois/clicktoplugin#154]
When I load a web page with an embedded video, sometimes I when drag the slider to a position in the video and the video will not appropriately seek and display the image for that time.

If I then click on the play button, I can drag the slider and it will update.

I can't reproduce this 100% of the time, even with the same video and reloading the page.  It may be that the preload of a video isn't working properly (I do have that setting turned on.)

**Comment by hoyois** [comment]
This isn't under CTP's control.
