### ISSUE TITLE
Unfortunately, c2p sucks for youtube now

### ISSUE THREAD

**Issue by ballo** [hoyois/clicktoplugin#157]
For some reason s2p now loads videos like the youtube html5 player instead of how it used to (it used to just blindly download and play the mp4). This is pretty obvious because clicking to an earlier part of the video will cause the player to re-download the video just like youtube's idiotic player. 

The work-around is to right-click the desired bitrate in the popup window, copy link, go to QuickTime Player, type command-L, paste, return, and play. If I go all of that, the videos play flawlessly. Clicking the video in Safari however will cause it to herk, jerk, and fail spectacularly.

Needless to say, this sucks.

The "QT Player" menu option hasn't worked for me since Snow Leopard. I'm currently using Yosemite (fresh install, no prefs ported).

**Comment by hoyois** [comment]
There's nothing CTP can do about how Safari handles video playback.
