### ISSUE TITLE
No H.264 YouTube support when ClickToPlugin is enabled

### ISSUE THREAD

**Issue by clemens-schulz** [hoyois/clicktoplugin#159]
YouTube's HTML5 player no longer works when ClickToPlugin is enabled, because YouTube no longer recognizes H.264 support.
##### Steps to reproduce:
1. Visit https://www.youtube.com/html5
2. Make sure there is a checkmark next to "H.264"
3. Install/Enable ClickToPlugin.
4. Repeat step 1 and 2
##### Expected result:

H.264 is supported (checkmark next to "H.264")
##### Actual result:

H.264 is only supported (exclamation mark next to "H.264") when ClickToPlugin is disabled/not installed

**Comment by hoyois** [comment]
This is on purpose, see http://hoyois.github.io/safariextensions/clicktoplugin/help.xhtml#faq_youtubesafari8
