### ISSUE TITLE
brightcove videos on pcworld.com

### ISSUE THREAD

**Issue by MacTheApple** [hoyois/clicktoplugin#161]
If you go to an article on pcworld.com, you'll notice that there is a video in the upper right of the page that shows the click to flash overlay, but underneath it, the video is still playing. From looking at the code to the page, it appears that it loads both a flash .swf and a html5 player, and CTP is only blocking the flash version. Is there any way to make it block both of them?
Here's an ironic example:

http://www.pcworld.com/article/2858421/websites/how-to-stop-autoplay-videos.html

**Comment by hoyois** [comment]
No, CTP can't block HTML5 videos.
