### ISSUE TITLE
YouTube update prevents loading of HTML5 video

### ISSUE THREAD

**Issue by ben-marko** [hoyois/clicktoplugin#162]
Recent update to YouTube prevents loading of HTML5 video. Plugin appears to work, then when video is selected (clicked) the video never plays - it seems to get stuck or frozen. 
![screen shot 2016-02-06 at 5 30 12 am](https://cloud.githubusercontent.com/assets/17097652/12866890/bae4d6de-cc92-11e5-8bd5-68c1f7dd75a2.jpg)

**Comment by hoyois** [comment]
It looks like you have the "Initial behavior" set to "Do not preload". Then you have to press Play to launch the video.

**Comment by ben-marko** [comment]
That did it! Thank you, I am not sure how that changed. I never change the default settings. But many thanks nonetheless -
