### ISSUE TITLE
BBC news stopped again

### ISSUE THREAD

**Issue by JohnBlackburne** [hoyois/clicktoplugin#99]
Not all but it seems to be most new ones, not just the ones you'd expect such as sports ones with rights restrictions. E.g.

http://www.bbc.co.uk/news/science-environment-30497303
http://www.bbc.co.uk/news/world-africa-30508008
http://www.bbc.co.uk/news/world-asia-30508004
http://www.bbc.co.uk/news/uk-30508667

**Comment by DOFfactory** [comment]
Stopped working again? Using `https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/BBC.js` in the PLugin to HTML5 conversion scripts, updated on July 29, 2015.

**Comment by hoyois** [comment]
Still works for me...

**Comment by DOFfactory** [comment]
I can see only the "Download Flash plugin" message. Can you give me a link that works for you? Just as an example...

**Comment by hoyois** [comment]
Ah that explains it: there's no Flash on BBC unless you have Flash installed.

**Comment by DOFfactory** [comment]
Am I missing something here? Isn't the purpose of Flash2Html5 conversion script to request html5 instead of flash? To my knowledge, iPads are able to play BBC videos in HTML5: https://www.youtube.com/watch?v=8BHUzP13YXY
